/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

/**
 *
 * @author ferna
 */
public class FormPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton1 = new javax.swing.JButton();
        AreaTrabalho = new javax.swing.JDesktopPane();
        Local = new javax.swing.JButton();
        Pessoa = new javax.swing.JButton();
        Esquema = new javax.swing.JButton();
        Marca = new javax.swing.JButton();
        Dependente = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro");

        AreaTrabalho.setBackground(new java.awt.Color(51, 51, 51));

        Local.setBackground(new java.awt.Color(102, 0, 102));
        Local.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Local.setForeground(new java.awt.Color(255, 255, 255));
        Local.setText("Local");
        Local.setBorder(null);
        Local.setBorderPainted(false);
        Local.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LocalActionPerformed(evt);
            }
        });

        Pessoa.setBackground(new java.awt.Color(102, 0, 102));
        Pessoa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Pessoa.setForeground(new java.awt.Color(255, 255, 255));
        Pessoa.setText("Pessoa");
        Pessoa.setBorder(null);
        Pessoa.setBorderPainted(false);
        Pessoa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PessoaActionPerformed(evt);
            }
        });

        Esquema.setBackground(new java.awt.Color(102, 0, 102));
        Esquema.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Esquema.setForeground(new java.awt.Color(255, 255, 255));
        Esquema.setText("Esquema");
        Esquema.setBorder(null);
        Esquema.setBorderPainted(false);
        Esquema.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EsquemaActionPerformed(evt);
            }
        });

        Marca.setBackground(new java.awt.Color(102, 0, 102));
        Marca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Marca.setForeground(new java.awt.Color(255, 255, 255));
        Marca.setText("Marca");
        Marca.setBorder(null);
        Marca.setBorderPainted(false);
        Marca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MarcaActionPerformed(evt);
            }
        });

        Dependente.setBackground(new java.awt.Color(102, 0, 102));
        Dependente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Dependente.setForeground(new java.awt.Color(255, 255, 255));
        Dependente.setText("Dependente");
        Dependente.setBorder(null);
        Dependente.setBorderPainted(false);
        Dependente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DependenteActionPerformed(evt);
            }
        });

        AreaTrabalho.setLayer(Local, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaTrabalho.setLayer(Pessoa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaTrabalho.setLayer(Esquema, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaTrabalho.setLayer(Marca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaTrabalho.setLayer(Dependente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout AreaTrabalhoLayout = new javax.swing.GroupLayout(AreaTrabalho);
        AreaTrabalho.setLayout(AreaTrabalhoLayout);
        AreaTrabalhoLayout.setHorizontalGroup(
            AreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaTrabalhoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(AreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Dependente, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(Marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Esquema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Local, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(675, Short.MAX_VALUE))
        );
        AreaTrabalhoLayout.setVerticalGroup(
            AreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaTrabalhoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Local, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Esquema, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DependenteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DependenteActionPerformed
    {//GEN-HEADEREND:event_DependenteActionPerformed
        FormDependente form = new FormDependente(this, true);
        // form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Dependente");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_DependenteActionPerformed

    private void MarcaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MarcaActionPerformed
    {//GEN-HEADEREND:event_MarcaActionPerformed
        FormMarca form = new FormMarca(this, true);
        // form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Marcas");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_MarcaActionPerformed

    private void EsquemaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EsquemaActionPerformed
    {//GEN-HEADEREND:event_EsquemaActionPerformed
        FormEsquema form = new FormEsquema(this, true);
        // form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Esquema");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_EsquemaActionPerformed

    private void PessoaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PessoaActionPerformed
    {//GEN-HEADEREND:event_PessoaActionPerformed
        FormPessoa form = new FormPessoa(this, true);
        // form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Pessoa");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_PessoaActionPerformed

    private void LocalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LocalActionPerformed
    {//GEN-HEADEREND:event_LocalActionPerformed
        FormLocal form = new FormLocal(this, true);
        // form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Local");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_LocalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                FormPrincipal form = new FormPrincipal();
                form.setLocationRelativeTo(null);
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane AreaTrabalho;
    private javax.swing.JButton Dependente;
    private javax.swing.JButton Esquema;
    private javax.swing.JButton Local;
    private javax.swing.JButton Marca;
    private javax.swing.JButton Pessoa;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
